Repository theohbrothers/docker-easyrsa, pull requests merged in 2023-09, with the labels that each got.

#28 Refactor: Move versions from `VARIANTS.ps1` to `versions.json`
  generate/definitions/VARIANTS.ps1
  generate/definitions/versions.json
Labels: refactor

#29 Enhancement (ci): Add `Update-Versions.ps1` and `cron` job
  .github/workflows/cron.yml
  Update-Versions.ps1
  generate/definitions/FILES.ps1
  generate/templates/.github/workflows/cron.yml.ps1
Labels: enhancement

#30 Enhancement (ci): Add `on: merge_group` for merge queue support
  .github/workflows/ci-master-pr.yml
  generate/templates/.github/workflows/ci-master-pr.yml.ps1
Labels: enhancement

#31 Docs (readme): Move base image note to top of readme
  README.md
  generate/templates/README.md.ps1
Labels: docs

#33 Enhancement: Add v3.1.4 variants
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v3.1.4/Dockerfile
  variants/v3.1.4/docker-compose.yml
  variants/v3.1.4/docker-entrypoint.sh
Labels: enhancement

#34 Enhancement: Add v3.1.3 variants
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v3.1.3/Dockerfile
  variants/v3.1.3/docker-compose.yml
  variants/v3.1.3/docker-entrypoint.sh
Labels: enhancement

#35 Enhancement: Add v3.1.0 variants
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v3.1.0/Dockerfile
  variants/v3.1.0/docker-compose.yml
  variants/v3.1.0/docker-entrypoint.sh
Labels: enhancement

#37 Enhancement: Add v3.0.2 variants
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v3.0.2/Dockerfile
  variants/v3.0.2/docker-compose.yml
  variants/v3.0.2/docker-entrypoint.sh
Labels: enhancement

#36 Enhancement: Add v3.0.9 variants
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  generate/templates/Dockerfile.ps1
  variants/v3.0.9/Dockerfile
  variants/v3.0.9/docker-compose.yml
  variants/v3.0.9/docker-entrypoint.sh
Labels: enhancement

#38 Enhancement: Add `easyrsa` to `PATH`, and store PKI in `/data/pki`
  README.md
  generate/templates/Dockerfile.ps1
  generate/templates/README.md.ps1
  generate/templates/docker-entrypoint.sh.ps1
  variants/v3.0.1/Dockerfile
  variants/v3.0.1/docker-entrypoint.sh
  variants/v3.0.2/Dockerfile
  variants/v3.0.2/docker-entrypoint.sh
  variants/v3.0.3/Dockerfile
  variants/v3.0.3/docker-entrypoint.sh
  variants/v3.0.4/Dockerfile
  variants/v3.0.4/docker-entrypoint.sh
  variants/v3.0.5/Dockerfile
  variants/v3.0.5/docker-entrypoint.sh
  variants/v3.0.6/Dockerfile
  variants/v3.0.6/docker-entrypoint.sh
  variants/v3.0.7/Dockerfile
  variants/v3.0.7/docker-entrypoint.sh
  variants/v3.0.8/Dockerfile
  variants/v3.0.8/docker-entrypoint.sh
  variants/v3.0.9/Dockerfile
  variants/v3.0.9/docker-entrypoint.sh
  variants/v3.1.0/Dockerfile
  variants/v3.1.0/docker-entrypoint.sh
  variants/v3.1.1/Dockerfile
  variants/v3.1.1/docker-entrypoint.sh
  variants/v3.1.2/Dockerfile
  variants/v3.1.2/docker-entrypoint.sh
  variants/v3.1.3/Dockerfile
  variants/v3.1.3/docker-entrypoint.sh
  variants/v3.1.4/Dockerfile
  variants/v3.1.4/docker-entrypoint.sh
  variants/v3.1.5/Dockerfile
  variants/v3.1.5/docker-entrypoint.sh
Labels: enhancement

#32 Enhancement: Add v3.1.6 variants
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v3.1.6/Dockerfile
  variants/v3.1.6/docker-compose.yml
  variants/v3.1.6/docker-entrypoint.sh
Labels: enhancement

#39 Enhancement: Remove unneeded `iptables`
  generate/templates/Dockerfile.ps1
  variants/v3.0.1/Dockerfile
  variants/v3.0.2/Dockerfile
  variants/v3.0.3/Dockerfile
  variants/v3.0.4/Dockerfile
  variants/v3.0.5/Dockerfile
  variants/v3.0.6/Dockerfile
  variants/v3.0.7/Dockerfile
  variants/v3.0.8/Dockerfile
  variants/v3.0.9/Dockerfile
  variants/v3.1.0/Dockerfile
  variants/v3.1.1/Dockerfile
  variants/v3.1.2/Dockerfile
  variants/v3.1.3/Dockerfile
  variants/v3.1.4/Dockerfile
  variants/v3.1.5/Dockerfile
  variants/v3.1.6/Dockerfile
Labels: enhancement

#40 Fix: Remove `/root/.gnupg` after removing `gnupg`
  generate/templates/Dockerfile.ps1
  variants/v3.0.1/Dockerfile
  variants/v3.0.2/Dockerfile
  variants/v3.0.3/Dockerfile
  variants/v3.0.4/Dockerfile
  variants/v3.0.5/Dockerfile
  variants/v3.0.6/Dockerfile
  variants/v3.0.7/Dockerfile
  variants/v3.0.8/Dockerfile
  variants/v3.0.9/Dockerfile
  variants/v3.1.0/Dockerfile
  variants/v3.1.1/Dockerfile
  variants/v3.1.2/Dockerfile
  variants/v3.1.3/Dockerfile
  variants/v3.1.4/Dockerfile
  variants/v3.1.5/Dockerfile
  variants/v3.1.6/Dockerfile
Labels: fix

#41 Docs (readme): Update Variant versions section
  README.md
  generate/templates/README.md.ps1
Labels: docs

#42 Enhancement (ci): Remove ` $env:GITHUB_TOKEN` in `Update-Versions.ps1`
  Update-Versions.ps1
Labels: enhancement

#43 Refactor (ci): Use new `versions.json` config
  Update-Versions.ps1
  generate/definitions/VARIANTS.ps1
  generate/definitions/versions.json
Labels: refactor

#44 Enhancement (ci): Add `workflow_dispatch` to `cron` job
  .github/workflows/cron.yml
  generate/templates/.github/workflows/cron.yml.ps1
Labels: enhancement

#46 Fix: Sleep 1 second before cleaning up `/root/.gnupg` to avoid race condition error
  generate/templates/Dockerfile.ps1
  variants/v3.0.1/Dockerfile
  variants/v3.0.2/Dockerfile
  variants/v3.0.3/Dockerfile
  variants/v3.0.4/Dockerfile
  variants/v3.0.5/Dockerfile
  variants/v3.0.6/Dockerfile
  variants/v3.0.7/Dockerfile
  variants/v3.0.8/Dockerfile
  variants/v3.0.9/Dockerfile
  variants/v3.1.0/Dockerfile
  variants/v3.1.1/Dockerfile
  variants/v3.1.2/Dockerfile
  variants/v3.1.3/Dockerfile
  variants/v3.1.4/Dockerfile
  variants/v3.1.5/Dockerfile
  variants/v3.1.6/Dockerfile
Labels: fix

#45 Enhancement (ci): Add support for incremental variants
  .github/workflows/ci-master-pr.yml
  generate/templates/.github/workflows/ci-master-pr.yml.ps1
Labels: enhancement

#47 Fix (docker-entrypoint.sh): Fix detection of `easyrsa` subcommands for 3.1.6
  generate/templates/docker-entrypoint.sh.ps1
  variants/v3.0.1/docker-entrypoint.sh
  variants/v3.0.2/docker-entrypoint.sh
  variants/v3.0.3/docker-entrypoint.sh
  variants/v3.0.4/docker-entrypoint.sh
  variants/v3.0.5/docker-entrypoint.sh
  variants/v3.0.6/docker-entrypoint.sh
  variants/v3.0.7/docker-entrypoint.sh
  variants/v3.0.8/docker-entrypoint.sh
  variants/v3.0.9/docker-entrypoint.sh
  variants/v3.1.0/docker-entrypoint.sh
  variants/v3.1.1/docker-entrypoint.sh
  variants/v3.1.2/docker-entrypoint.sh
  variants/v3.1.3/docker-entrypoint.sh
  variants/v3.1.4/docker-entrypoint.sh
  variants/v3.1.5/docker-entrypoint.sh
  variants/v3.1.6/docker-entrypoint.sh
Labels: fix

#48 Fix: Fix error removing `/root/.gnupg`
  generate/templates/Dockerfile.ps1
  variants/v3.0.1/Dockerfile
  variants/v3.0.2/Dockerfile
  variants/v3.0.3/Dockerfile
  variants/v3.0.4/Dockerfile
  variants/v3.0.5/Dockerfile
  variants/v3.0.6/Dockerfile
  variants/v3.0.7/Dockerfile
  variants/v3.0.8/Dockerfile
  variants/v3.0.9/Dockerfile
  variants/v3.1.0/Dockerfile
  variants/v3.1.1/Dockerfile
  variants/v3.1.2/Dockerfile
  variants/v3.1.3/Dockerfile
  variants/v3.1.4/Dockerfile
  variants/v3.1.5/Dockerfile
  variants/v3.1.6/Dockerfile
Labels: fix
